services:
  postgres:
    image: postgres:latest
    container_name: postgres_scale_api
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "8543:5432"
    volumes:
      - scale_api_postgres_data:/var/lib/postgresql/data
volumes:
  scale_api_postgres_data:
